### ISSUE TITLE
Error loading Private Key

### ISSUE THREAD

**Issue by ArchiFleKs** [bloxapp/ssv#267]
Hi, I have tried to generate multiple time a private key with the documentation:

```
docker run -d --name=ssv_node_op_key -it 'bloxstaking/ssv-node:latest' \
/go/bin/ssvnode generate-operator-keys && docker logs ssv_node_op_key --follow \
&& docker stop ssv_node_op_key && docker rm ssv_node_op_key
```

I pass the configuration like this:

```
  eth2:
    Network: "prater"
    BeaconNodeAddr: "http://prater-lighthouse-beacon-rpc.ethereum:5052"
  eth1:
    ETH1Addr: ws://goerli-geth-rpc.ethereum:8546
  OperatorPrivateKey: "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBeFBrNFIrR2JvMHlzTHYvYWRTN25BbnJ5dmhaMGF5aU5oRXlzaDBvWk9RSGhLMG5qCkRpankxZEFNTUFLTmxpeTEwL3YzaGVXQyt6MVJ4dnY0dG55RDU2b1Z1WjY1eWdaMVcvMjlQYkROMGFlSjYzMTgKOW4rMXlXejMwb0E5SDczbWNPdmRYK0NBdmFFWkI0aVVBdXVvM1pMVDIvc3FzWGFhQklGVEFtQjdUOWgvV3krQQpiS3V0eGFZd0RkT25NMCtadis4ekpXQjQ2VHFXU2FqbmNpRmNpWTNVdjVHYmFyckVuMEZYS3ZlRjVyYlpDY1BDCmRpOUl6bFoxUFFSL085bGV3M2JCRTl6MVNSVS9TL0RGVWtHVmhSRnVjdWRRdWp0OVdRN2Z5L3JsSyt2M0JjckcKSGJ6ZUxBaVBLb2xyaXplY0I2WVVjcTlzTHdzcW56cFZ4RmxmMlFJREFRQUJBb0lCQUFwNHBVRk5BUlVoVWxYOQpUQVBHeG9rZk9DQmEyVDJKSGx6V0pxWGFqcFMxUU44b1FtWFNUM2FHWk45NGcwWmtnaFlPNHcyL01jTmhjeU44CjZhL3AxcWxPSlhHRXVxTyt6Q1pqeXRlb3VvaFd1OEpGSFl1TkpvRGF4aUh1cDFFMHF6ZDlrbnN5V0NXOGxyUUwKMHJLRkRLa2EwU0IwcmNSWlpiNnZrVllqQXVzdm8xSENBSEpTaE9rUW1NSERsMDViNkJlY1hpWjJ4bmw2OG54NAowTWpmWC94eXNQMHNDMEtHN0RRWVAwL2VPaVBZbUFvczJzWSs2SVhWT3J4Wjc1QXJqc2Z6a1dPODdGZy9Gejg1CmlpVmZUbzlETHloek1MSE1IRzR3eXZPcFM3WkJ2V2F2YmpHSE9qNFFvcmN1c3UwbytqZEpzODRPd3d5MHdKckoKbmh1SXo3RUNnWUVBMk50a3VmL1p4MzA0eWtLYjFzVDJMZjJxeEY3cEdScjhMbnRVdDUyTkEzTzRuV2RIU1Y5RQphUXlCUFBMUm5jN3o2c0Rwc3k4dlFOdDBBSlpGZUZ3MkRPUVFielV0YnljMFhFZzFub0RvRlZjZThjdzRxaEQ0ClF0UDJrWm9wWkJxVFNhT0IwTkxETEpQUnZkTXJpNVRmL0pVNGY0YkhrWGh4aDhIZ2JLeUFWSzhDZ1lFQTZJY0sKK3dNV0pPcmFBeWlvVGhWWjFDSlgvdUVsQWxKbXJKL3hDNDRITktjZnc5aW53UFNycGt6RDk0ZGtYT3N0N0p5TgpSeS96ZTdKamNVMVl3QzNpUzNGTmlFdU81Sy9oZ3djelF4MFNyQlAwWGRFZ215QTlMOFVVRzFCZUNxY2k2bnl0CkhsN2JiL1RoT3luLzlnUXAwV1NldTNFbmpYUGxYclhOcGJPenhmY0NnWUFCMXZxbnlVL2pyV0JKOXY2emQ4Qk8KNjVRRFRuclR4N0xVQWgvWjN2QlBVekFCeGRxSStOSHZ3amRtZVBqbVNkY3Y2cXNRNWhtVWgwZ1lxUzIxczdLUgpzVzJpUStVNnlDNWRpZzlLWlBXVEdNWWVid2tjQ0VEUzhGRnJNcytmRmNxaUdVMEVwSVViWDdXcjBwclArRmRlCklUWDFmd002YkxjcDI2ODN2TTdwNlFLQmdIRzdjNlI0eXdEOW1lckhuU0tzRU1iUWtZZktLYWJzRk9wRVJNc3AKQ2Q4NEN6Sm9xd3lXMzhvMGEvbUxVSXllUDFVbThYY3JQZ1YzcUdvSHNldzF4U1N2WTRQUnFTK3owekthZC9sUQpwQXhrcWphbERqU3gzUnViWW8xRmp1blkvQndESlUzZ2lhWkYrVkJONTdNMk1Cb0tCQldjY0FNZzk4U09XZXE5CmJhWGJBb0dCQUlEci9nUmdUTFhxbEJOaFh5cDlrcmVDZmdldjVNeDM1YmdKaXFPQ1RBb0tyclhST29oVk54WkMKMEorZ282T2JuUUswVlk0aDlkb1VkdHZjTjJwZTl1Yll2UlJlTFpZNXYyTWVSVE5zVkM4SlR4K2RsZkUvd1NnRQpseFRQbGJka295YXNJbndHNDU3S29qUm1lQkVHVncvNVpvR0N6STc2NGZTek5JTXRJYkFBCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg=="
```

I get the following error which from my understanding is an issue for loading the operator key right ? :

```
2021/08/22 02:12:23 starting SSV-Node:v0.0.15
badger 2021/08/22 02:12:23 INFO: All 1 tables opened in 0s
badger 2021/08/22 02:12:23 INFO: Discard stats nextEmptySlot: 0
badger 2021/08/22 02:12:23 INFO: Set nextTxnTs to 1
badger 2021/08/22 02:12:23 INFO: Deleting empty file: /data/000129.vlog
2021-08-22T02:12:23.630495Z     INFO    kv/badger.go:45 Badger db initialized   {"app": "SSV-Node:v0.0.15"}
2021-08-22T02:12:23.630552Z     INFO    goclient/goclient.go:41 connecting to beacon client...  {"app": "SSV-Node:v0.0.15", "component": "goClient", "network": "prater"}
2021-08-22T02:12:24.194878Z     INFO    goclient/goclient.go:54 successfully connected to beacon client {"app": "SSV-Node:v0.0.15", "component": "goClient", "network": "prater", "name": "Standard (HTTP)", "address": "https://1pl4OI3LFPHVOmIc7JJ6zRHKTpO:1a23f9bde9eac64980b0103797d70384@eth2-beacon-prater.infura.io"}
2021-08-22T02:12:24.195500Z     INFO    p2p/p2p.go:93   Ip Address      {"app": "SSV-Node:v0.0.15", "component": "p2p", "ip": "10.0.145.162"}
2021-08-22T02:12:24.236965Z     INFO    p2p/p2p.go:113  listening on port       {"app": "SSV-Node:v0.0.15", "component": "p2p", "id": "16Uiu2HAkwSjXsDbTZUgJawLEMKnmjajtvtoReeKEfdsG1upkw3KP", "port": "/ip4/10.0.145.162/tcp/13000"}
2021-08-22T02:12:24.238694Z     INFO    p2p/discovery.go:297    using external IP       {"app": "SSV-Node:v0.0.15", "component": "p2p", "id": "16Uiu2HAkwSjXsDbTZUgJawLEMKnmjajtvtoReeKEfdsG1upkw3KP", "IP from config": "10.0.145.162", "IP": "10.0.145.162"}
2021-08-22T02:12:24.248794Z     INFO    p2p/discovery.go:312    using DNS IP    {"app": "SSV-Node:v0.0.15", "component": "p2p", "id": "16Uiu2HAkwSjXsDbTZUgJawLEMKnmjajtvtoReeKEfdsG1upkw3KP", "DNS": "node-0.ssv..domain", "IP": "34.244.113.78"}
2021-08-22T02:12:24.250043Z     INFO    p2p/discovery.go:222    ENR     {"app": "SSV-Node:v0.0.15", "component": "p2p", "id": "16Uiu2HAkwSjXsDbTZUgJawLEMKnmjajtvtoReeKEfdsG1upkw3KP", "enr": "enr:-Jy4QJ-eVeYhLZTeg3K4dmx3JDNrfKA546LOm5CiDwW3MZHSF_kgiNnCUmMoLn0jaPKdKPa1E6oSkAJ1L1FIvf70LUIBh2F0dG5ldHOIAAAAAAAAAACCaWSCdjSCaXCECgCRoolzZWNwMjU2azGhAh38-Nc-ufDi0XF2Xbg5pklRS5b1Arrgz3LasV3gT6Tyg3RjcIIyyIN1ZHCCLuA"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xf21ff2]

goroutine 1 [running]:
crypto/x509.IsEncryptedPEMBlock(...)
        /usr/local/go/src/crypto/x509/pem_decrypt.go:100
github.com/bloxapp/ssv/utils/rsaencryption.ConvertPemToPrivateKey(0xc00baea500, 0x498, 0x498, 0xc00baea500, 0x498)
        /go/src/github.com/bloxapp/ssv/utils/rsaencryption/rsa_encryption.go:57 +0x72
github.com/bloxapp/ssv/operator.(*storage).GetPrivateKey(0xc00ba7cee0, 0xc000103000, 0x0, 0x900)
        /go/src/github.com/bloxapp/ssv/operator/storage.go:61 +0x17d
github.com/bloxapp/ssv/operator.(*storage).verifyPrivateKeyExist(0xc00ba7cee0, 0xc00b62ae00, 0x68f, 0xc00b62ae00, 0x68f, 0x690, 0x0, 0x0)
        /go/src/github.com/bloxapp/ssv/operator/storage.go:119 +0x2f
github.com/bloxapp/ssv/operator.(*storage).SetupPrivateKey(0xc00ba7cee0, 0xc000169200, 0x8c0, 0x2891db0, 0x1d9bcc0)
        /go/src/github.com/bloxapp/ssv/operator/storage.go:76 +0xc5
github.com/bloxapp/ssv/cli/operator.glob..func1(0x277a880, 0xc000a91b40, 0x0, 0x2)
        /go/src/github.com/bloxapp/ssv/cli/operator/node.go:108 +0xc86
github.com/spf13/cobra.(*Command).execute(0x277a880, 0xc000a91b00, 0x2, 0x2, 0x277a880, 0xc000a91b00)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:854 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x2779620, 0x7, 0x1a33b08, 0x1)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/bloxapp/ssv/cli.Execute(0x1a39a40, 0x8, 0x1d2cae0, 0x7)
        /go/src/github.com/bloxapp/ssv/cli/cli.go:29 +0xa5
main.main()
        /go/src/github.com/bloxapp/ssv/cmd/ssvnode/main.go:16 +0x51
```

**Comment by ArchiFleKs** [comment]
My bad it is working when using the Makefile to run the node, I had some left over files inside the data folder also

**Comment by nivBlox** [comment]
Hey @ArchiFleKs, 
We have created a PR that should shed some light on why it fails for you. 

it will be include in the next version tag (v.0.0.16)

**Comment by ArchiFleKs** [comment]
> Hey @ArchiFleKs, 
> 
> Did you manage to pass your key? 
> 
> 
> 
> * Also we have created a PR that showing more informative logs about the use of the operator key. 
> 
> it will be include in the next version tag (v.0.0.16)
> 
> 
> 
> 

Hi, yes working fine I have some sag nodes running and also submitted some validators. I was trying to run the docker image directly without using the make file. And I also had some leftover files from previously failed attempts. 

With a clean /data and public IP and hostport available it is ok
