### ISSUE TITLE
"IP address is not accessible"

### ISSUE THREAD

**Issue by stefa2k** [bloxapp/ssv#348]
```
ssv_1            | 2021-10-06T05:48:54.151887Z  INFO    p2p/discovery.go:222    ENR     {"app": "SSV-Node:v0.0.20", "component": "p2p", "id": "16Uiu2HAm7W6ueScrLYcSBQSecNfQZagfpHk7VLbPj12U1fgNMDnC", "enr": "enr:-Jy4QDhcrboIPyoAjTNfViwZU1zteGFDt9HS_qYII9HZjA0GOuJ5OjfTY-CvAaoHR7dcqwiese1rFCucQQvYomRMdRQBh2F0dG5ldHOIAAAAAAAAAACCaWSCdjSCaXCEQRX52YlzZWNwMjU2azGhArNuwMrKSvRM9dVqse-YGZEkozfyFQJ-MGrdsMrCnKM9g3RjcIIyyIN1ZHCCLuA"}
ssv_1            | 2021-10-06T05:49:04.152380Z  ERROR   p2p/p2p.go:166  IP address is not accessible    {"app": "SSV-Node:v0.0.20", "component": "p2p", "id": "16Uiu2HAm7W6ueScrLYcSBQSecNfQZagfpHk7VLbPj12U1fgNMDnC", "error": "dial tcp 65.21.249.217:13000: i/o timeout"}
ssv_1            | panic: runtime error: invalid memory address or nil pointer dereference
ssv_1            | [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x14e54f5]
ssv_1            | 
ssv_1            | goroutine 1 [running]:
ssv_1            | github.com/bloxapp/ssv/network/p2p.New(0x1dc48a0, 0xc000040038, 0xc000ba8540, 0x28ff308, 0x6, 0xc0007b75e0, 0x12, 0xc000040a10)
ssv_1            |      /go/src/github.com/bloxapp/ssv/network/p2p/p2p.go:168 +0x1615
ssv_1            | github.com/bloxapp/ssv/cli/operator.glob..func1(0x27e7920, 0xc0007b3cd0, 0x0, 0x1)
ssv_1            |      /go/src/github.com/bloxapp/ssv/cli/operator/node.go:86 +0x8f0
ssv_1            | github.com/spf13/cobra.(*Command).execute(0x27e7920, 0xc0007b3cc0, 0x1, 0x1, 0x27e7920, 0xc0007b3cc0)
ssv_1            |      /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:854 +0x2c2
ssv_1            | github.com/spf13/cobra.(*Command).ExecuteC(0x27e66c0, 0x7, 0x1a6f1c8, 0x1)
ssv_1            |      /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
ssv_1            | github.com/spf13/cobra.(*Command).Execute(...)
ssv_1            |      /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
ssv_1            | github.com/bloxapp/ssv/cli.Execute(0x1a7513a, 0x8, 0x1d6bab0, 0x7)
ssv_1            |      /go/src/github.com/bloxapp/ssv/cli/cli.go:29 +0xa5
ssv_1            | main.main()
ssv_1            |      /go/src/github.com/bloxapp/ssv/cmd/ssvnode/main.go:16 +0x51
ssv_1            | make: *** [Makefile:61: start-node] Error 2
```

**Comment by stefa2k** [comment]
Error still present in `0.1.1`
